#+TITLE: Internship
#+STARTUP: overview
#+ROAM_TAGS: index
#+CREATED: [2021-06-14 Pzt]
#+LAST_MODIFIED: [2021-06-14 Pzt 20:20]

* Day 1
Mesai saati başladığında, Melih Bey beni çalıştıkları ARGE sahasının Elektrik tarafına götürüp, orada kendilerinin yaptığı bir PLC panelinin içeriğini ve nasıl çalıştığını anlattı. Panelin üst ortasında ve üst sağında iki tane PLC bulunuyor. Bu PLC'lerde biri Tia-Portal adlı programda çalışan projeler için uygun iken diğer PLC ise SIMATIC STEP 7 programında yapılan projeler için uyumlu. PLC tabanlı uygulamaların, Profibus ve Profinet diye iki tür haberleşme protokolü kullandığını öğrendim. Bu iki protokol için kullanılan kabloların, Profibus için olan mor ve kalın girişli, Profinet için olanı ise yeşil ve diğerine göre daha küçüktür. Çalışmalar sırasında Kaan Bey'den öğrendiğime göre göre bu bu bahsi geçen haberleşme protokollerinin kabloları 100 metreden daha uzun olmamalı. Olacaksa bile araya Repeater konulması şart. Yine Kaan Bey'den öğrendiğime göre, daha uzun mesafeler arasındaki haberleşmeler için profibus ve profinet yerine Uydu teknolojileri kullanılır. Bunun için SIM kartlar kullanılıyormuş.

Data sheet ve manuallerde "DP" ile başlayan pinler, Profibus'ı, "PN" ile başlayan pinler ise Profinet haberleşme protokollerinin kullanılacağını belirtir.

Elektrik tarafında çalışırken, üç büyük servo motorun elektrik tehsisatında Kaan Bey ve İlker Bey'e yardımcı oldum. Tehsisat bittiğinde Kaan bey, bu motorları test etmek için kullandığı yazılımları tek tek tanıtıp üstünde ayrıntılı olarak anlatımlar yaptı. SEW yazılımı ile motorları test ettik. TIA Portal yazılımını ise kullanmadık ancak bu yazılım elde PLC yokken, bilgisayarın CPU'sunu PLC gibi kullanmamızı sağladığını öğrendim. Kaan bey mesai bitiminde bana TIA Portal için kendi çekmiş olduğu dersleri ve bu programların içinde yüklü olduğu sanal makineyi vererek bana çok büyük bir katkıda bulundu.

Endüstriyel elektronik cihazlarda turuncu kablo, o cihaza gelen güç kesildiğinde bile hala güç veren kabloyu temsil eder. Bu kablo ve teknik, örnek olarak sürücüsü olan bir servo motor duraan vaziyette olmasına rağmen hala sürücü ile PLC'nin haberleşmesini mümkün kılar.

Endüstride kullanılan motorların genellikle "Emergency" ve "Application" gibi modları olur. Application modunda çalışan bir motoru durdurduğumuzda, bağlı olduğu cihazın athaletini emmek için yavaşlayarak dururken, "Emergency" modunda motor aniden durur. Kaan Bey'in dediğine göre Emergency durumcunda motorların durma süresinin 0.1 değerine çekilmesi gerekiyor.

Kaan Bey'den öğrendiğim kadarıyla, Endüstriyel otomasyon çözümleri üreten bir firma olarak her zaman müşteriye verilecek olan kullanım kılavuzları, (Manual) çok düzgün ve net anlaşılır olmalıdır. Hatta eğer yabancı müşterilere ürün satışı yapılacaksa kılavuzlar, yeminli tercümanlara çevirtilip öyle sunulması gerekir. Bunun bu kadar ciddiye alınmasının nedeni, yanlış anlaşılan her hangi bir cümlenin, can kaybı ile sonuçlanıp çok yüksek miktarlarda Tazminat davasının açılması ihtimalidir.

Compac motorlar, yine Endüstride kullanılan motor çeşitlerinden biridir. Bu motor türü, üzerinde kendi sürücüsüyle gelen motor çeşididir. Mühendisler bu sürücülere, motorun çalışmasını istedikleri şekle uygun olarak belli başlı parametreler gönderip, programlarlar. Bu sayede geriye kalan tek şey motora güç verip çalıştırmak olur. Sürücüsü olmayan motorlar ise "Sürücü Modülü" adlı bir cihazla kontrol edilir. Motor bu cihaza bağlanır ve cihazın üzerindeki potansiyometre, istenilen yön, dönme hızı'na göre ayarlanır.
