#+title: Anki
#+startup: content
* notitia
** 20:17
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:ANKI_DECK: notitia
:ANKI_NOTE_ID: 1653758959208
:END:
*** Front
if a *name* of a variable, class or function _needs a comment_ then the name does not reveal its ...
*** Back
intent
** 20:25
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:ANKI_DECK: notitia
:ANKI_NOTE_ID: 1653758959306
:END:
*** Front
why including the word "list" in a variable name is a bad thing?
*** Back
because people might assume that this is actually a *list* or *array* object.
** 20:27
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:ANKI_DECK: notitia
:ANKI_NOTE_ID: 1653758959405
:END:
*** Front
which alternative word should be used instead *list* in an object name?
*** Back
if it's not actually a list or array, use *group* or use "s" to represent quantity
** 20:48 :clean_code:
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:ANKI_DECK: notitia
:ANKI_NOTE_ID: 1653760554056
:END:
*** Front
which 2 words should be used when we use variables for *copying* or *moving* from one directoion to another
*** Back
*source* and *destination*
** 20:54 :clean_code:
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:ANKI_DECK: notitia
:ANKI_NOTE_ID: 1653760554161
:END:
*** Front
why using *pronounceable* names important?
*** Back
because *pronouncing*, *discussing* about this variable will be easier. also *searching* is easier.
** 21:02 :clean_code:
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:ANKI_DECK: notitia
:ANKI_NOTE_ID: 1653761082931
:END:
*** Front
why using *encodings* like *Hungarian Notation* is a bad idea?
*** Back
because it add a *metal load* to the code. programmer will need to _decipher_ every variable name. also *searching* is *hard*. and *miss spelling* them is easy!
** 21:07 :java:
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:ANKI_DECK: notitia
:ANKI_FAILURE_REASON: cannot create note because it is a duplicate
:END:
*** Front
how to reference class properties in java?
*** Back
#+begin_src java
this.your_property
#+end_src
** 22:19 :clean_code:
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:ANKI_DECK: notitia
:ANKI_NOTE_ID: 1653766195648
:END:
*** Front
is including *verb* words inside *class names* good idea?
*** Back
No. It should be *noun*
** 22:23 :programming:
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:ANKI_DECK: notitia
:ANKI_NOTE_ID: 1653766195749
:END:
*** Front
what *predicate method* means in programming?
*** Back
methods that return *boolean* like ~true~ or ~false~
** 22:27 :clean_code:
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:ANKI_DECK: notitia
:ANKI_NOTE_ID: 1653766195823
:END:
*** Front
how *predicate methods* should be named?
*** Back
~isEven()~, ~isEmpty()~ and so on.
** 22:32 :clean_code:
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:ANKI_DECK: notitia
:ANKI_NOTE_ID: 1653766561148
:END:
*** Front
what is *accessor method* means?
*** Back
it accesses a *property* of a class
** 22:33 :clean_code:
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:ANKI_DECK: notitia
:ANKI_NOTE_ID: 1653766561223
:END:
*** Front
what *mutator method* means?
*** Back
it mutates (changes) a *property or a class*
** 22:34 :clean_code:
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:ANKI_DECK: notitia
:ANKI_NOTE_ID: 1653766561323
:END:
*** Front
how *mutator methods* should be names?
*** Back
use ~set~ prefix. like ~setName("savolla")~
** 22:35 :clean_code:
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:ANKI_DECK: notitia
:ANKI_NOTE_ID: 1653766561398
:END:
*** Front
how *accessor methods* should be names?
*** Back
use ~get~ prefix. like ~getName()~
** 22:37 :clean_code:
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:ANKI_DECK: notitia
:ANKI_NOTE_ID: 1653769018124
:END:
*** Front
what is *static factory* methods?
*** Back
TODO
** 22:58 :clean_code:
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:ANKI_DECK: notitia
:ANKI_NOTE_ID: 1653769018199
:END:
*** Front
what is *punning* in coding?
*** Back
it's where you use words which has *multiple meanings*. like ~add()~. where it can be understood as *summing* or *inserting*
** 23:01 :clean_code:
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:ANKI_DECK: notitia
:ANKI_NOTE_ID: 1653769018273
:END:
*** Front
what is the better word alternative than *add* when you adding some element to an *array* or *list*?
*** Back
*append*
** 23:02 :clean_code:
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:ANKI_DECK: notitia
:ANKI_NOTE_ID: 1653769018349
:END:
*** Front
what is the better word alternative than *add* when you _summing values_?
*** Back
~sum~
** 23:05 :clean_code:
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:ANKI_DECK: notitia
:ANKI_NOTE_ID: 1653769018423
:END:
*** Front
what is *visitor pattern*?
*** Back
TODO
** 23:08 :clean_code:
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:ANKI_DECK: notitia
:ANKI_NOTE_ID: 1653769018499
:END:
*** Front
is using *problem domain concept names* as variable,class names a good idea?
*** Back
yes.
